name: DeathLocation
version: '${project.version}'
main: com.eferrante.deathlocation.DeathLocation
author: "Edoardo Ferrante"
api-version: '1.20'
commands:
  deathlocation:
    description: Main command for DeathLocation plugin
    aliases: [dl]